export type { Creatable } from "./creatable"
export type { Deletable } from "./deletable"
export type { Findable } from "./findable"
export type { Repository } from "./repository"
export type { Saveable } from "./saveable"
