export type { Creatable } from "./creatable.ts"
export type { Deletable } from "./deletable.ts"
export type { Findable } from "./findabe.ts"
export type { Repository } from "./repository.ts"
export type { Saveable } from "./saveble.ts"
